import sys
import hashlib
import zipfile
import os

def calculate_sha256(data):
    sha256_hash = hashlib.sha256()
    sha256_hash.update(data)
    return sha256_hash.hexdigest()

def main():
    if len(sys.argv) < 3:
        print("Usage: python generate_hashes.py <path_to_apk> <path_to_header>")
        sys.exit(1)

    apk_path = sys.argv[1]
    header_path = sys.argv[2]

    dex_hash = ""
    lib_hash = ""

    # In a real multidex scenario, we would hash all classes*.dex and combine their hashes.
    # For this script we will hash all classes*.dex found in the APK.
    dex_hashes = []
    
    with zipfile.ZipFile(apk_path, 'r') as apk:
        # Find all classes*.dex
        dex_files = [f for f in apk.namelist() if f.startswith('classes') and f.endswith('.dex')]
        dex_files.sort()
        
        combined_dex_data = b""
        for dex in dex_files:
            combined_dex_data += apk.read(dex)
            
        dex_hash = calculate_sha256(combined_dex_data)
        
        # Read libsecurity_checks.so (assume arm64-v8a for primary check)
        lib_path = 'lib/arm64-v8a/libsecurity_checks.so'
        if lib_path in apk.namelist():
            lib_data = apk.read(lib_path)
            lib_hash = calculate_sha256(lib_data)
        else:
            print(f"Warning: {lib_path} not found in APK.")
            lib_hash = "MISSING"

    # Generate Header
    header_content = f"""#pragma once

// Auto-generated by CI/CD
// Do not modify manually

constexpr char EXPECTED_DEX_HASH[] = "{dex_hash}";
constexpr char EXPECTED_LIB_HASH[] = "{lib_hash}";
"""

    with open(header_path, 'w') as f:
        f.write(header_content)

    print(f"Hashes generated and written to {header_path}")
    print(f"DEX Hash: {dex_hash}")
    print(f"LIB Hash: {lib_hash}")

if __name__ == "__main__":
    main()
