import { securityLogger } from './SecurityLogger';

/**
 * In a real production application, this service would accept the JWS string
 * generated by the Android Play Integrity API, then either:
 * 1. Verify the signature locally using Google's public certificates.
 * 2. Send the token to the Google Play Developer API for server-to-server validation.
 *
 * Since we are testing in an emulator without a real Play Console configuration,
 * this is a Mock Verifier that simulates the Google validation logic.
 */

export interface PlayIntegrityVerdict {
  isValid: boolean;
  deviceRecognitionVerdict: string[]; // e.g., ["MEETS_DEVICE_INTEGRITY"]
  appRecognitionVerdict: string;      // e.g., "PLAY_RECOGNIZED"
  accountDetails: string;             // e.g., "LICENSED"
  errorMessage?: string;
}

class PlayIntegrityService {
  private static instance: PlayIntegrityService;
  
  // Used for Fault Injection Testing
  private forceReject: boolean = false;

  private constructor() {}

  public static getInstance(): PlayIntegrityService {
    if (!PlayIntegrityService.instance) {
      PlayIntegrityService.instance = new PlayIntegrityService();
    }
    return PlayIntegrityService.instance;
  }

  public setFault(forceReject: boolean) {
    this.forceReject = forceReject;
  }

  /**
   * Simulates cryptographic verification of the JWS token
   */
  public verifyToken(token: string, expectedNonce: string): PlayIntegrityVerdict {
    console.log(`[PlayIntegrityService] Verifying JWS Token (Nonce: ${expectedNonce})`);

    // 1. Fault Injection Check (A7 testing)
    if (this.forceReject) {
      console.error('[PlayIntegrityService] ⚠️ FAULT INJECTION: Rejecting valid token.');
      return {
        isValid: false,
        deviceRecognitionVerdict: [],
        appRecognitionVerdict: 'UNRECOGNIZED_VERSION',
        accountDetails: 'UNLICENSED',
        errorMessage: 'Mock validation failed due to injected fault.'
      };
    }

    // 2. Validate format (mock check)
    if (!token || typeof token !== 'string' || token.length < 20) {
      return {
        isValid: false,
        deviceRecognitionVerdict: [],
        appRecognitionVerdict: 'UNRECOGNIZED_VERSION',
        accountDetails: 'UNLICENSED',
        errorMessage: 'Invalid or missing JWS token format.'
      };
    }

    // 3. Simulate parsing the Payload 
    // In our mobile app, SecurityManager.getBackendAttestationPayload returns a JSON string,
    // not a true JWS, so we'll just parse the JSON for this simulation.
    try {
      const payload = JSON.parse(token);
      
      // Check Nonce binding (Crucial for preventing Replay Attacks)
      if (payload.nonce !== expectedNonce) {
        return {
          isValid: false,
          deviceRecognitionVerdict: [],
          appRecognitionVerdict: 'PLAY_RECOGNIZED',
          accountDetails: 'LICENSED',
          errorMessage: `Nonce mismatch. Expected ${expectedNonce}, got ${payload.nonce}`
        };
      }

      // Check Risk Level from our Native Module
      if (payload.nativeRiskLevel === 'TAMPERED' || payload.nativeRiskLevel === 'COMPROMISED') {
         return {
          isValid: false,
          deviceRecognitionVerdict: [],
          appRecognitionVerdict: 'PLAY_RECOGNIZED',
          accountDetails: 'LICENSED',
          errorMessage: `Device reported compromised status: ${payload.nativeRiskLevel}`
        };
      }

      // 4. Return successful attestation
      return {
        isValid: true,
        deviceRecognitionVerdict: ['MEETS_DEVICE_INTEGRITY', 'MEETS_BASIC_INTEGRITY'],
        appRecognitionVerdict: 'PLAY_RECOGNIZED',
        accountDetails: 'LICENSED'
      };

    } catch (e) {
       return {
        isValid: false,
        deviceRecognitionVerdict: [],
        appRecognitionVerdict: 'UNRECOGNIZED_VERSION',
        accountDetails: 'UNLICENSED',
        errorMessage: 'Failed to parse attestation payload.'
      };
    }
  }
}

export const playIntegrityService = PlayIntegrityService.getInstance();
