apply plugin: 'com.android.library'
android {
    ndkVersion "26.1.10909125"
    compileSdk 36
    namespace "com.learningapp.securitynative"
    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 36
        externalNativeBuild { cmake { cppFlags "-std=c++17" } }
    }
    externalNativeBuild { cmake { path "src/main/cpp/CMakeLists.txt" } }
}
